replicaCount: 1

image:
  repository: jhontero/k8s
  tag: "e3627a6f3153296351dcf89fc7a0c8cd7e6df4fc"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi