replicaCount: 1

image:
  repository: jhontero/K8S
  tag: "4e67e1d558ca943c5fa31d393e5e49f45fd41f3a"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi