replicaCount: 1

image:
  repository: jhontero/k8s
  tag: "a15a276ebdb19f1a149a349452fbf19d61b3a797"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi